site_name: xcube Viewer
repo_url: https://github.com/xcube-dev/xcube-viewer
repo_name: xcube-dev/xcube-viewer

copyright: Copyright &copy; 2026 Brockmann Consult

nav:
  - About: index.md
  - User Guide:
      - user_guide/index.md
      - "Getting Started": user_guide/getting_started.md
      - "Analyse Variables": user_guide/analyse.md
      - "Colour Mapping": user_guide/colormaps.md
      - "Adjust Settings": user_guide/settings.md
  - Get your own Viewer:
      - build_viewer/index.md
      - "Ways to use xcube Viewer": build_viewer/ways_to_use.md
      - "Viewer Configuration": build_viewer/config_viewer.md
      - "Create User Panels": build_viewer/panels.md
  - General Concepts: concepts.md
  - Feature References: features.md

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logos/logo512.png
  favicon: assets/logos/logo192.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - navigation.top
    - navigation.indexes
    # - navigation.sections
    # - navigation.expand
    # - navigation.tabs
    # - toc.integrate
    - toc.permalink
    - toc.follow
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra:
  demo_url: https://bc-viewer.brockmann-consult.de
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xcube-dev/xcube-viewer

plugins:
  - search
  - autorefs

extra_css:
  - css/custom.css
